services:
  - type: web
    name: deal-bot
    env: python
    buildCommand: ""
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8465346144:AAGSHC77UkXVZZTUscbYItvJxgQbBxmFcWo
